server:
  port: 8081

#\u6570\u636E\u5E93\u914D\u7F6E\u9879
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis\u914D\u7F6E\u9879
mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath*:mybatis/mapper/**/*.xml

#pagehelper\u914D\u7F6E\u9879
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

#\u6253\u5370Mybatis\u751F\u6210\u7684SQL
logging:
  level:
    com.kangswx.springbootmybatispagehelper.mapper: debug
